##############################
# EDC Postgres Configuration #
##############################
postgresql:
  auth:
    postgresPassword: <path:traceability-irs/data/dev/controlplane#databasepassword>
    password: <path:traceability-irs/data/dev/controlplane#databasepassword>

##################################
# EDC Controlplane Configuration #
##################################
edc-controlplane:
  ingresses:
    - enabled: true
      hostname: "irs-edc-test.dev.demo.catena-x.net"
      annotations:
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      endpoints:
        - protocol
        - management
      className: ""
      tls:
        - hosts:
            - "irs-edc-test.dev.demo.catena-x.net"
          secretName: tls-secret
      certManager:
        issuer: ""
        clusterIssuer: ""

  edc:
    postgresql:
      password: <path:traceability-irs/data/dev/controlplane#databasepassword>
    transfer:
      proxy:
        token:
          verifier:
            publickey:
              alias: irs-dev-daps-cert-consumer
          signer:
            privatekey:
              alias: irs-dev-daps-cert-consumer-key
    api:
      auth:
        key: "123456"
    controlplane:
      url: "https://irs-edc-test.dev.demo.catena-x.net"
    dataplane:
      url: "https://irs-edc-test-dataplane.dev.demo.catena-x.net"
  configuration:
    properties: |-
      edc.oauth.client.id=<path:traceability-irs/data/dev/controlplane#edc.oauth.client.id>
      edc.oauth.private.key.alias=irs-dev-daps-cert-consumer-key
      edc.oauth.provider.jwks.url=https://daps-irs.dev.demo.catena-x.net/.well-known/jwks.json
      edc.oauth.certificate.alias=irs-dev-daps-cert-consumer
      edc.oauth.token.url=https://daps-irs.dev.demo.catena-x.net/token
      edc.vault.hashicorp.url=https://vault.demo.catena-x.net
      edc.vault.hashicorp.token=<path:traceability-irs/data/dev/controlplane#vaultToken>
      edc.vault.hashicorp.api.secret.path=/v1/traceability-irs/data
      edc.data.encryption.keys.alias=irs-dev-daps-cert-consumer-key
      edc.data.encryption.algorithm=NONE

###############################
# EDC Dataplane Configuration #
###############################
edc-dataplane:
  edc:
    api:
      auth:
        key: "123456"
  ## Ingress declaration to expose the network service.
  ingresses:
    ## Public / Internet facing Ingress
    - enabled: true
      # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
      hostname: "irs-edc-test-dataplane.dev.demo.catena-x.net"
      # -- Additional ingress annotations to add
      annotations:
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # -- EDC endpoints exposed by this ingress resource
      endpoints:
        - public
      # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
      className: "nginx"
      # -- Enables TLS on the ingress resource
      tls:
        - hosts:
            - "irs-edc-test-dataplane.dev.demo.catena-x.net"
          # Default secret for certificate creation already provided to your namespace
          secretName: tls-secret
      ## Adds [cert-manager](https://cert-manager.io/docs/) annotations to the ingress resource
      certManager:
        # -- If preset enables certificate generation via cert-manager namespace scoped issuer
        issuer: ""
        # -- If preset enables certificate generation via cert-manager cluster-wide issuer
        clusterIssuer: ""

  configuration:
    properties: |-
      edc.oauth.client.id=<path:traceability-irs/data/dev/controlplane#edc.oauth.client.id>
      edc.oauth.private.key.alias=irs-dev-daps-cert-consumer-key
      edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
      edc.oauth.provider.jwks.url=https://daps-irs.dev.demo.catena-x.net/.well-known/jwks.json
      edc.oauth.certificate.alias=irs-local-daps-cert-consumer
      edc.oauth.token.url=https://daps-irs.dev.demo.catena-x.net/token
      edc.vault.hashicorp.url=https://vault.demo.catena-x.net
      edc.vault.hashicorp.token=<path:traceability-irs/data/dev/controlplane#vaultToken>
      edc.vault.hashicorp.api.secret.path=/v1/traceability-irs
