blobstore:
  persistence:
    storeType: MINIO
    minio:
      endpoint: http://localhost:9000
      accessKey: minioadmin
      secretKey: minioadmin

digitalTwinRegistry:
  type: decentral

irs:
  job:
    cleanup:
      scheduler:
        completed: 0 * * * * *
        failed: 0 * * * * *
    jobstore:
      ttl:
        failed: PT1H
        completed: PT1H
  security:
    api:
      keys:
        admin: 01234567890123456789
        regular: 09876543210987654321

spring:
  security:
    oauth2:
      client:
        provider:
          common:
            token-uri: https://localhost
  redis:
    host: localhost
    port: 6379
    password: redispwd

# ESS Module specific properties
ess:
  irs:
    url: http://localhost:8080

irs-edc-client:
  async-timeout: PT10M
  controlplane:
    datareference:
      storage:
        useRedis: true
