---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edc-dataplane.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-dataplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.edc.endpoints.default.port }}
      targetPort: default
      protocol: TCP
      name: default
    - port: {{ .Values.edc.endpoints.control.port }}
      targetPort: control
      protocol: TCP
      name: control
    - port: {{ .Values.edc.endpoints.public.port }}
      targetPort: public
      protocol: TCP
      name: public
    - port: {{ .Values.edc.endpoints.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.edc.endpoints.observability.port }}
      targetPort: observability
      protocol: TCP
      name: observability
    - port: {{ .Values.edc.endpoints.management.port }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "edc-dataplane.selectorLabels" . | nindent 4 }}