test_name: Make sure investigation job with invalid request is handled correctly with MOCK

strict:
  - headers:off
  - json:off

stages:
  - name: register a BPN investigation with invalid request
    request:
      url: "{tavern.env_vars.IRS_HOST}/ess/bpn/investigations"
      json:
        globalAssetId111: urn:uuid:2c57b0e9-a653-411d-bdcd-64787e9fd3a7
        incidentBpns11:
          - BPNL00000003B6LU
      method: POST
      headers:
        content-type: application/json
        $ext:
          function: local.testing.api-tests.tavern_helpers:create_bearer_token
    response:
      status_code: 400
      verify_response_with:
        function: local.testing.api-tests.tavern_helpers:errors_for_invalid_investigation_request_are_correct
      json:
        statusCode: BAD_REQUEST
        error: "Invalid Arguments."
      headers:
        content-type: application/json


---


test_name: Make sure investigation job with valid globalAssetId and BPN is processed correctly with MOCK

strict:
  - headers:off
  - json:off

stages:
  - name: register a BPN investigation with valid globalAssetId
    request:
      url: "{tavern.env_vars.IRS_ESS_HOST}/ess/bpn/investigations"
      json:
        globalAssetId: urn:uuid:2c57b0e9-a653-411d-bdcd-64787e9fd3a7
        bomLifecycle: asPlanned
        callbackUrl: http://testikus.com
        incidentBpns:
          - BPNL00000003B6LU
      method: POST
      headers:
        content-type: application/json
        $ext:
          function: local.testing.api-tests.tavern_helpers:create_bearer_token
    response:
      status_code: 201
      headers:
        content-type: application/json
      save:
        json:
          job_id: id

  - &verify_ESS_job_response_with_desired_test_steps_and_wait_up_to_15_minutes_for_COMPLETED
    name: verify job response with desired test steps and wait for desired job status
    max_retries: 30
    request:
      url: "{tavern.env_vars.IRS_ESS_HOST}/ess/bpn/investigations/{job_id}"
      params:
        returnUncompletedJob: true
      method: GET
      headers:
        content-type: application/json
        $ext:
          function: local.testing.api-tests.tavern_helpers:create_bearer_token
    response:
      status_code: 200
      json:
        job:
          state: COMPLETED
    delay_after: 30

  - name: get response for created investigation
    request:
      url: "{tavern.env_vars.IRS_ESS_HOST}/ess/bpn/investigations/{job_id}"
      params:
        returnUncompletedJob: true
      method: GET
      headers:
        content-type: application/json
        $ext:
          function: local.testing.api-tests.tavern_helpers:create_bearer_token
    response:
      status_code: 200
      verify_response_with:
        - function: local.testing.api-tests.tavern_helpers:supplyChainImpacted_is_correct_in_submodels_for_valid_ID
      headers:
        content-type: application/json


---


test_name: Make sure server process job after authorization (1.0.0)

strict:
  - headers:off
  - json:off

stages:
  - name: create a job and check for success
    request:
      url: "{tavern.env_vars.IRS_HOST}/irs/jobs"
      json:
        key:
          globalAssetId: "{tavern.env_vars.GLOBAL_ASSET_ID_AS_PLANNED}"
          bpn: "BPNL00000003AYRE"
      method: POST
      headers:
        content-type: application/json
        $ext:
          function: local.testing.api-tests.tavern_helpers:create_bearer_token
    response:
      status_code: 201
      headers:
        content-type: application/json
      save:
        json:
          job_id: id
    delay_after: 1

  - name: verify job response with desired test steps
    request:
      url: "{tavern.env_vars.IRS_HOST}/irs/jobs/{job_id}"
      params:
        returnUncompletedJob: true
      method: GET
      headers:
        content-type: application/json
        $ext:
          function: local.testing.api-tests.tavern_helpers:create_bearer_token
    response:
      status_code: 200
      headers:
        content-type: application/json
