test-edc:
  participant:
    id: BPNL00000003CRHK
  controlplane:
    ingresses:
      - enabled: true
        hostname: "irs-test-controlplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret

    endpoints:
      management:
        authKey: "123456"

    internationalDataSpaces:
      id: TXDC
      description: Tractus-X Eclipse IDS Data Space Connector
      title: ""
      maintainer: ""
      curator: ""
      catalogId: TXDC-Catalog

    # Explicitly declared url for reaching the ids api (e.g. if ingresses not used)
    url:
      ids: ""

  dataplane:
    ingresses:
      - enabled: true
        hostname: "irs-test-dataplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret

    # Explicitly declared url for reaching the public api (e.g. if ingresses not used)
    url:
      public: ""


  postgresql:
    enabled: true
    auth:
      database: "edc"
      username: "<path:traceability-irs/data/dev/controlplane#databaseuser>"
      password: "<path:traceability-irs/data/dev/controlplane#databasepassword>"
    username: "<path:traceability-irs/data/dev/controlplane#databaseuser>"
    password: "<path:traceability-irs/data/dev/controlplane#databasepassword>"
    jdbcUrl: "jdbc:postgresql://postgresql-hl:5432/edc"

  vault:
    hashicorp:
      url: "https://vault.demo.catena-x.net"
      token: "<path:traceability-irs/data/dev/controlplane#vaultToken>"
      timeout: 30
      healthCheck:
        enabled: true
        standbyOk: true
      paths:
        secret: /v1/traceability-irs
        health: /v1/sys/health
    secretNames:
      transferProxyTokenSignerPrivateKey: dev-test-consumer-key
      transferProxyTokenSignerPublicKey: dev-test-consumer
      transferProxyTokenEncryptionAesKey: test-edc-encryption-key
      dapsPrivateKey: dev-test-consumer-key
      dapsPublicKey: dev-test-consumer

  daps:
    url: "https://daps-irs.dev.demo.catena-x.net"
    clientId: 49:DA:E3:5C:86:5F:E1:B3:6B:48:98:96:8A:36:68:84:AF:31:63:75:keyid:49:DA:E3:5C:86:5F:E1:B3:6B:48:98:96:8A:36:68:84:AF:31:63:75
    paths:
      jwks: /.well-known/jwks.json
      token: /token

  backendService:
    httpProxyTokenReceiverUrl: "https://irs-submodel-server3.dev.demo.catena-x.net/data/endpoint-data-reference"

postgresql:
  enabled: false
