name: IRS Cucumber Integration Test execution

on:
  workflow_call: # Trigger by another workflow
    secrets:
      regularUserApiKey:
        required: true
      adminUserApiKey:
        required: true
      cucumberPublishToken:
        required: true
    inputs:
      executionFilter:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests with Maven
        env:
          REGULAR_USER_API_KEY: ${{ secrets.regularUserApiKey }}
          ADMIN_USER_API_KEY: ${{ secrets.adminUserApiKey }}
          ISSUE_FILTER: ${{ inputs.executionFilter }}
          CUCUMBER_PUBLISH_TOKEN: ${{ secrets.cucumberPublishToken }}
        run: mvn clean verify -P cucumber -Dgroups="$ISSUE_FILTER" -pl irs-cucumber-tests -am --batch-mode

      - name: Publish Cucumber Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          files: |
            irs-cucumber-tests/target/cucumber-junit-report.xml

