name: IRS Load Test

on:
  workflow_dispatch: # Trigger manually
    inputs:
      irs-host:
        type: choice
        description: IRS environment to test
        default: 'https://item-relationship-service-a.integration.cofinity-x.com'
        required: true
        options:
          - 'https://item-relationship-service-a.integration.cofinity-x.com'
          - 'https://item-relationship-service-b.integration.cofinity-x.com'
      irs-admin-api-key:
        description: IRS Admin API Key
        required: true
      simulation-class:
        description: 'Select the simulation class to run'
        required: true
        default: 'simulation.SynchonizationSimulation'
        options:
          - 'org.eclipse.tractusx.irs.JobSimulation'
          - 'org.eclipse.tractusx.irs.OrderSimulation'
      simulation-duration:
        description: 'The duration of the test in seconds'
        required: true
        type: number
        default: 1
      assets-with-childs:
        description: 'Should assets with child elements be used?'
        required: true
        type: boolean
        default: false

jobs:

  check-config:
    runs-on: ubuntu-latest
    steps:
      - name: mask token
        run: |
          API_KEY=$(jq -r '.inputs.irs-admin-api-key' $GITHUB_EVENT_PATH)
          echo ::add-mask::$API_KEY
          echo API_KEY=$API_KEY >> $GITHUB_ENV

  gatling-test:
    needs: check-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Gatling tests
        env:
          IRS_HOST: ${{ github.event.inputs.irs-host }}
          SCENARIO_DURATION: ${{ github.event.inputs.simulation-duration }}
          ASSETS_WITH_CHILDS: ${{ github.event.inputs.assets-with-childs }}
          API_KEY: ${{ env.API_KEY }}
        run: |
          mvn gatling:test -pl irs-load-tests -Dgatling.simulationClass=${{ simulation-class }}

      - name: Archive Report
        uses: actions/upload-artifact@v4
        with:
          name: gatling-report
          path: irs-load-tests/target/gatling/

      - name: Archive job duration data
        uses: actions/upload-artifact@v4
        if: ${{ exists('irs-load-tests/target/job-duration.csv') }}
        with:
          name: job-duration-report
          path: irs-load-tests/target/job-duration.csv

