name: "OWASP dependency scanner v2"

on:
  workflow_dispatch: # Additionally allow to trigger manually

  push:
    branches: main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches: main
    paths:
      - '**/pom.xml'
      - 'pom.xml'
      - '.config/owasp-suppressions.xml'
  schedule:
    - cron: '0 0 * * *' # Once a day

env:
  FAIL_BUILD_ON_CVSS: 7
  SUPPRESSIONS_FILE: .config/owasp-suppressions.xml

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    name: owasp-check
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: run maven owasp plugin
        run: mvn --batch-mode clean package -DskipTests

      - name: Dependency check irs-api # possible severity values: <'fail'|'warn'|'ignore'>
        uses: dependency-check/Dependency-Check_Action@3102a65fd5f36d0000297576acc56a475b0de98d
        with:
          project: 'irs-api'
          path: 'irs-api'
          format: 'HTML'
          out: 'irs-api/target/depcheck-report.html'
          args: >
            --failOnCVSS ${{ env.FAIL_BUILD_ON_CVSS }}
            --suppression ${{ env.SUPPRESSIONS_FILE }}
        env:
          # actions/setup-java changes JAVA_HOME, so it needs to be reset to match the depcheck image
          JAVA_HOME: /opt/jdk

      - name: Upload results for irs-api
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report tx-backend
          path: irs-api/target/depcheck-report.html
