name: "Quality Checks (Release Guidelines)"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  check-quality:
    name: Check quality guidelines
    uses: eclipse-tractusx/sig-infra/.github/workflows/reusable-quality-checks.yaml@main
    secrets: inherit