name: Tavern IRS API tests on INT

on:
  workflow_dispatch: # Trigger manually
    inputs:
      irs-host:
        type: string
        description: IRS environment to test
        default: 'https://irs.int.demo.catena-x.net'
        required: true
      irs-ess-host:
        type: string
        description: IRS-ESS environment to test
        default: 'https://irs-ess.int.demo.catena-x.net'
        required: true
      global-asset-id-asPlanned:
        type: string
        description: Global Asset ID to use for the asPlanned tests
        default: 'urn:uuid:0733946c-59c6-41ae-9570-cb43a6e4c79e'
        required: true
      bpn-asPlanned:
        type: string
        description: BPN to use for the asPlanned Global Asset ID
        default: 'BPNL00000003AYRE'
        required: true
      global-asset-id-asBuild:
        type: string
        description: Global Asset ID to use for the asBuild tests
        default: 'urn:uuid:7940e0cc-7814-41eb-8b04-d984a325deec'
        required: true
      bpn-asBuild:
        type: string
        description: BPN to use for the asBuild Global Asset ID
        default: 'BPNL00000003AYRE'
        required: true
      execution-ticket:
        type: string
        description: JIRA execution ticket to safe results in.
        default: 'TRI-910'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7

      - name: Install dependencies
        run: |
          pip install pytest
          pip install py
          pip install tavern
          pip list

      - name: Run tests
        env:
          IRS_HOST: ${{ 'https://irs.int.demo.catena-x.net' }}
          IRS_ESS_HOST: ${{ github.event.inputs.irs-ess-host || 'https://irs-ess.int.demo.catena-x.net' }}
          KEYCLOAK_HOST: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_TOKEN_URI }}
          KEYCLOAK_CLIENT_ID: ${{ secrets.ORG_IRS_OAUTH2_CLIENT_ID_INT }}
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.ORG_IRS_OAUTH2_CLIENT_SECRET_INT }}
          GLOBAL_ASSET_ID_AS_PLANNED: ${{ github.event.inputs.global-asset-id-asPlanned || 'urn:uuid:0733946c-59c6-41ae-9570-cb43a6e4c79e' }}
          BPN_AS_PLANNED: ${{ github.event.inputs.bpn-asPlanned || 'BPNL00000003AYRE' }}
          GLOBAL_ASSET_ID_AS_BUILD: ${{ github.event.inputs.global-asset-id-asBuild || 'urn:uuid:7940e0cc-7814-41eb-8b04-d984a325deec' }}
          BPN_AS_BUILD: ${{ github.event.inputs.bpn-asBuild || 'BPNL00000003AYRE' }}
        run: |
          python -m pytest local/testing/api-tests/irs-api-tests.tavern.yaml --junitxml=tavern-results.xml

      - name: Upload results
        if: always()
        env:
          JIRA_USERNAME: ${{ secrets.ORG_IRS_JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.ORG_IRS_JIRA_PASSWORD }}
          TEST_EXECUTION_TICKET: ${{ github.event.inputs.execution-ticket || 'TRI-910' }}
        # Remove tokens and upload the tavern results to JIRA Test execution
        run: |
          sed "s/access_tok.*:s = '.*'//g" tavern-results.xml | sed "s/Authorization: Bearer .*/Authorization:/g" | uniq > result.xml
          curl -H "Content-Type: multipart/form-data" \
          -u $JIRA_USERNAME:$JIRA_PASSWORD \
          -F 'file=@result.xml' \
          "https://jira.catena-x.net/rest/raven/1.0/import/execution/junit?testExecKey=$TEST_EXECUTION_TICKET"
